@startuml
用户 -> 网站 ++: 输入网址
网站 -> 网关 --++: 跳转到网关
网关 -> Oauth2认证中心 --++: 网关发现未认证，\n跳转到认证中心
Oauth2认证中心 -> 用户 --++: 返回用户授权登录界面
用户 -> Oauth2认证中心 --++: 用户登录
Oauth2认证中心 -> 网关 --++: 返回授权码code
网关 -> 网站 --++: 定向到业务服务
网站 -> 网关 --++: 携带token正常调用接口
网关 -> 网关 : 校验与鉴权
网关 -> 业务服务 --++: 转发到业务服务
业务服务 -> 网站 --: 返回相应资源
@enduml
